# Generated by Django 4.1.2 on 2025-02-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="due_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="helper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helper",
                to="nibble.nibbleprofile",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="order_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="nibble.nibbleprofile",
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="order_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="order_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nibble.nibbleprofile",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="order_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nibble.tasktype",
            ),
        ),
    ]
