# Generated by Django 4.1.2 on 2025-02-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0002_alter_card_description_alter_card_due_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nibble.label",
            ),
        ),
    ]
