# Generated by Django 4.1.2 on 2025-02-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0003_column_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="label",
        ),
        migrations.AddField(
            model_name="card",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nibble.label",
            ),
        ),
    ]
