# Generated by Django 4.1.2 on 2025-02-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0005_remove_card_label_card_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="nibble.card",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="nibble.column",
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklists",
                to="nibble.card",
            ),
        ),
        migrations.AlterField(
            model_name="column",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="nibble.board",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="belongs_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nibble.card"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="checklist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="nibble.checklist",
            ),
        ),
    ]
