# Generated by Django 4.1.2 on 2025-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0006_alter_attachment_card_alter_card_column_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="belongs_to",
            new_name="card",
        ),
    ]
