# Generated by Django 4.1.2 on 2025-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0008_nibbleprofile_handle_alter_comment_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nibbleprofile",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="nibbleprofile",
            name="handle",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
