# Generated by Django 4.1.2 on 2025-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0010_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="icon",
            field=models.CharField(default="r", max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="label",
            field=models.ManyToManyField(blank=True, to="nibble.label"),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
