# Generated by Django 4.1.2 on 2025-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nibble", "0011_tasktype_icon_alter_card_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("H", "High"), ("N", "Normal"), ("L", "Low")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="icon",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
