# Generated by Django 4.1.2 on 2025-04-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nibble", "0013_remove_task_due_datetime_task_due_date_task_due_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "board_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nibble.board",
                    ),
                ),
            ],
            bases=("nibble.board",),
        ),
        migrations.AlterField(
            model_name="nibbleprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nibbleProfile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
